### ISSUE TITLE
confirm. att meddelande skickats från kontaktformulär

### ISSUE THREAD

**Issue by inglasarnas** [inglasarnas/inglasarna#3]
Typ en grön material ui toast för att meddelandet skickats, en röd toast för att meddelandet ej kunde skickas (beroende på svar från server)

**Comment by Sidlo98** [comment]
Har fixat så man kan skicka via kontakt formulären till netlify och sedan sätta upp sin mail för att få det dit med.

Det som behöver göras mera är att lägga till Response i GUI. :)
